### ISSUE TITLE
Feature: User can create a tournament

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can use a form to create a tournament.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When in the tournament tab, user can click the 'Create Tournament' button which will bring them to a page containing a form to be filled which set up the details of a tournament.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82009814/126532096-dfba8cc4-c895-4b5c-8d00-0d7dea3d9db2.png)
![image](https://user-images.githubusercontent.com/82009814/126532324-1ce4d4ff-95d9-4271-a1c6-ef416d42783e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create schema: Reel'n
- [x] Update `schema.sql` to create a table: tournaments
- [x] Update 'schema.sql' to create a table: tourneyRules

### ☁️ Server

- [x] Set up Express server with staticMiddleware & errorMiddleware
- [x] Create an endpoint for a POST request
  - [x] INSERT tournament forms into tourneyRules table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Make tournament nav icon go to tournaments page.
- [x] Create a 'New Tournament' button that goes to 'Create Tournament' page.
- [x] Create a component: <TournamentForm />.
  - [x] Child components: TourneyNameInput, TourneyPhotoInput, TourneyDurationInput, TourneyTypeInput, MinWeightInput, MinLengthInput,  PointSystem, AdditionalRulesTextarea.
- [x] Style all components in styles.css.
- [x] 'Create Tournament' button calls fetch for POST method to update db.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
