### ISSUE TITLE
Feature: Issue 6 User can log catches and submit to selected tournament/s

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/final-project#11]
## ⚙️ Feature

User can log catches and submit to selected tournament/s

## 📐 Functionality

On any page of the app, the user can click 'Log Catch' on the nav to go to a new page where they can fill out a form to enter details of a fish including a photo, the weight of the fish, the length of the fish and which tournament to submit it to. When they click the submit button, the log will be saved to the 'catches' table.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/82009814/127371697-87096330-6831-4ed0-b8e2-be2464e6c6c4.png)
![image](https://user-images.githubusercontent.com/82009814/127371732-c0a89a9e-7f87-40a4-9213-208ae1f987d7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to remove the 'score' field in the 'catches' table.

### ☁️ Server

- [x] Create a POST endpoint to INSERT catch details into the 'catches' table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a page component called 'log-catch'.
  - [x] Include form inputs for: image upload, weight, length, a 'select' drop-down menu for 'current' tournaments.
  - [x] Include a 'submit' button to call a fetch request inserting the form details into the DB.
  - [x] Include a cancel button to go back to 'tournaments' page. 
- [x] Create a 'calc-score.js' file to calculate the score of the log based on tournament scoring rules.
- [x] Update 'score-card' component to show user details and calculated score.
- [x] Update 'tourney' component to have a 'go back' button which routes back to 'tournaments' page.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
