### ISSUE TITLE
Feature: User can view a list of open tournaments

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see a list of tournaments that are 'open'.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the 'Tournaments' nav icon, they will be brought to the 'Tournaments' page where they can see a list of 'open' tournaments. They can also see some info like the name of the tournament, the duration in which it occurs, and the amount of people participating.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82009814/126538501-dc2caeeb-d997-4de7-ba3c-c782748cdeca.png)
![image](https://user-images.githubusercontent.com/82009814/126536814-a5bf846b-1a2b-4a67-aa97-eebbd28ed321.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create table: participants

### ☁️ Server

- [x] Create an endpoint for a GET request
  - [x] SELECT tourneyName, startDate, endDate, # of participants, public
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component: <TournamentList>
- [x] Create child component: <TournamentCard>
  - [x] Tourney name, duration, # of participants
- [x] Populate list with all tournaments that have public=true
- [x] Call fetch on 'tournament' nav icon for GET method to load <TournamentCard> attributes
- [x] Style <TournamentList> and <TournamentCard>

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
