### ISSUE TITLE
Issue 3: User can view details of an open tournament

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of an open tournament

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Starting on the home page, the user can click on a nav link to go to the tournaments page to see a list of open tournaments. If the user clicks a tournament card, they will be brought to that tournament's details page. On that page, they will have an option to click a button to join that tournament if the max number of participants has not yet been reached.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82009814/127030575-3bbffa8d-3e0c-4b9d-aec7-2bdc6d8f5075.png)
![image](https://user-images.githubusercontent.com/82009814/127030640-25b2dedc-59fa-40b5-9ec8-24b92fa3a47a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to add a 'maxParticipants' field to 'tourneyDetails' table.

### ☁️ Server

- [x] Update `server/index.js` to create an endpoint selecting all fields in 'tourneyDetails' table.
- [x] Update 'get('/api/tourneys')' to select 'maxParticipants' field.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a 'Tourney' page to show tourney details.
  - [x] Create 'ScoreCard' Component to show 'avatar', 'firstName', 'lastName', points, and standing.
    - [x] Include 'hide/show' tab for leader board.
  - [x] Add 3 view-swapping tabs: "Rules", "Recent Catches", "Chat"
  - [x] Fill "Rules" tab with tournament rules.
- [x] Update 'create-tourney-form' to include input for max participants.
- [x] Update 'Card' component to show number of participants out of max participants.

### 🧑‍⚕️ Clean Up
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
