### ISSUE TITLE
Issue 4: User can join an open tournament 

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can join an open tournament.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On a tournament's details page, user can click the 'Join Tournament' button to join an open spot for an open tournament. A modal will pop up for confirmation.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to create a POST endpoint to INSERT a 'userId' and 'tourneyId' to the 'participants' table.
- [x] Create GET endpoint to grab all columns from 'users' table where 'userId' = the user using the app.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update app.jsx to check X-Access-Token and save fetch user data from 'users' table.
- [x] Add a 'Join Tournament' button if user is not host.
  - [x] onClick, fetch a post request to add userId & tourneyId to 'participants' table.
- [x] Update 'Card' component to state the number of participants in each tournament.
- [x] Update 'TourneyForm' component to add userId to 'tourneyDetails' table as host's userId.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
