### ISSUE TITLE
Feature: Issue 5: User can view list of past/current tournaments

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view list of past/current tournaments depending on the date the tournament ends.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the 'tournaments' page, the user can click the slider buttons to filter tournaments they were a part of. If they click 'Past', tournaments that have ended already will show, if they click 'Current', tournaments currently happening will show.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82009814/127255601-a2c9ebaa-06ea-4082-adb2-6d5a01e6167d.png)
![image](https://user-images.githubusercontent.com/82009814/127255611-f97f7d33-459f-4e1f-82a4-e35eeb5cee35.png) 
![image](https://user-images.githubusercontent.com/82009814/127256286-8f03b27c-8de7-4d14-8d8e-d0f55094157c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to create an endpoint to GET tournaments filtered by endDate.
  - [x] Change the GET('/api/tourneys') to only select rows WHERE "endDate" is before today's date.
  - [x] Make a similar endpoint to select rows WHERE "endDate" is after today's date.
    - [x] Make sure these endpoints only show the tournaments with the user's userId in 'participants' table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update 'Card' component to show what place the user was in when the tournament ended.
  - [x] If user clicked 'Current', show the tournament's startDate & endDate
- [x] Update the sliders to change background colors when they are clicked.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
